"""empty message

Revision ID: 0a345bdadcab
Revises: 6806749fc5d9
Create Date: 2023-09-29 09:22:35.902740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a345bdadcab'
down_revision = '6806749fc5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('anzsic_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('anzsic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
