"""empty message

Revision ID: 362536fb8b2c
Revises: 1c09fc24ad9b
Create Date: 2023-07-29 16:20:23.169302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362536fb8b2c'
down_revision = '1c09fc24ad9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcode', schema=None) as batch_op:
        batch_op.alter_column('sa3_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sa4_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcode', schema=None) as batch_op:
        batch_op.alter_column('sa4_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sa3_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
