"""empty message

Revision ID: 5d73f6d05c96
Revises: af86a3ab1e06
Create Date: 2023-09-27 09:11:08.301482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d73f6d05c96'
down_revision = 'af86a3ab1e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_constraint('organisation_abn_key', type_='unique')
        batch_op.drop_constraint('organisation_address_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.create_unique_constraint('organisation_address_key', ['address'])
        batch_op.create_unique_constraint('organisation_abn_key', ['abn'])

    # ### end Alembic commands ###
