"""empty message

Revision ID: 6513b2f0b193
Revises: 36a7759d44e8
Create Date: 2023-09-26 20:01:15.160149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6513b2f0b193'
down_revision = '36a7759d44e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anzsic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('description')
    )
    op.create_table('business_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('description')
    )
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abn', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('anzsic_id', sa.Integer(), nullable=False),
    sa.Column('business_code_id', sa.Integer(), nullable=False),
    sa.Column('postcode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anzsic_id'], ['anzsic.id'], ),
    sa.ForeignKeyConstraint(['business_code_id'], ['business_code.id'], ),
    sa.ForeignKeyConstraint(['postcode_id'], ['postcode.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abn'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation')
    op.drop_table('business_code')
    op.drop_table('anzsic')
    # ### end Alembic commands ###
