"""empty message

Revision ID: af86a3ab1e06
Revises: bfbdd327992a
Create Date: 2023-09-27 09:08:51.301366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af86a3ab1e06'
down_revision = 'bfbdd327992a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('postcode_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('postcode_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
