"""empty message

Revision ID: b34add8d70b0
Revises: fcde86b3ea29
Create Date: 2023-07-29 15:07:07.010250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34add8d70b0'
down_revision = 'fcde86b3ea29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sa3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sa4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.Column('locality', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('sa3_id', sa.Integer(), nullable=False),
    sa.Column('sa4_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sa3_id'], ['sa3.id'], ),
    sa.ForeignKeyConstraint(['sa4_id'], ['sa4.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcode')
    op.drop_table('sa4')
    op.drop_table('sa3')
    # ### end Alembic commands ###
