"""empty message

Revision ID: bfbdd327992a
Revises: 870e5e5dc6d4
Create Date: 2023-09-27 08:49:46.052692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbdd327992a'
down_revision = '870e5e5dc6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_code', schema=None) as batch_op:
        batch_op.drop_constraint('business_code_code_key', type_='unique')
        batch_op.drop_constraint('business_code_description_key', type_='unique')
        batch_op.create_unique_constraint('business_code_code_description', ['code', 'description'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_code', schema=None) as batch_op:
        batch_op.drop_constraint('business_code_code_description', type_='unique')
        batch_op.create_unique_constraint('business_code_description_key', ['description'])
        batch_op.create_unique_constraint('business_code_code_key', ['code'])

    # ### end Alembic commands ###
