name: container

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '*'
    branches:
      - 'main'

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      -
        name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt install -y qemu-user-static

      -
        name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: txacct 
          tags: latest ${{ github.sha }}
          archs: amd64, arm64
          containerfiles: |
            ./Containerfile

      -
        name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Push to Container Registry
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
