// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AlembicVersion     string
	Anzsic             string
	BusinessCode       string
	Organisation       string
	OrganisationSource string
	Postcode           string
	Sa3                string
	Sa4                string
	State              string
	Transaction        string
}{
	AlembicVersion:     "alembic_version",
	Anzsic:             "anzsic",
	BusinessCode:       "business_code",
	Organisation:       "organisation",
	OrganisationSource: "organisation_source",
	Postcode:           "postcode",
	Sa3:                "sa3",
	Sa4:                "sa4",
	State:              "state",
	Transaction:        "transaction",
}
