// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// BusinessCode is an object representing the database table.
type BusinessCode struct {
	ID          int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	Code        null.String `boil:"code" json:"code,omitempty" toml:"code" yaml:"code,omitempty"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`

	R *businessCodeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L businessCodeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BusinessCodeColumns = struct {
	ID          string
	Code        string
	Description string
}{
	ID:          "id",
	Code:        "code",
	Description: "description",
}

var BusinessCodeTableColumns = struct {
	ID          string
	Code        string
	Description string
}{
	ID:          "business_code.id",
	Code:        "business_code.code",
	Description: "business_code.description",
}

// Generated where

var BusinessCodeWhere = struct {
	ID          whereHelperint
	Code        whereHelpernull_String
	Description whereHelpernull_String
}{
	ID:          whereHelperint{field: "\"business_code\".\"id\""},
	Code:        whereHelpernull_String{field: "\"business_code\".\"code\""},
	Description: whereHelpernull_String{field: "\"business_code\".\"description\""},
}

// BusinessCodeRels is where relationship names are stored.
var BusinessCodeRels = struct {
	Organisations string
}{
	Organisations: "Organisations",
}

// businessCodeR is where relationships are stored.
type businessCodeR struct {
	Organisations OrganisationSlice `boil:"Organisations" json:"Organisations" toml:"Organisations" yaml:"Organisations"`
}

// NewStruct creates a new relationship struct
func (*businessCodeR) NewStruct() *businessCodeR {
	return &businessCodeR{}
}

func (r *businessCodeR) GetOrganisations() OrganisationSlice {
	if r == nil {
		return nil
	}
	return r.Organisations
}

// businessCodeL is where Load methods for each relationship are stored.
type businessCodeL struct{}

var (
	businessCodeAllColumns            = []string{"id", "code", "description"}
	businessCodeColumnsWithoutDefault = []string{}
	businessCodeColumnsWithDefault    = []string{"id", "code", "description"}
	businessCodePrimaryKeyColumns     = []string{"id"}
	businessCodeGeneratedColumns      = []string{}
)

type (
	// BusinessCodeSlice is an alias for a slice of pointers to BusinessCode.
	// This should almost always be used instead of []BusinessCode.
	BusinessCodeSlice []*BusinessCode
	// BusinessCodeHook is the signature for custom BusinessCode hook methods
	BusinessCodeHook func(context.Context, boil.ContextExecutor, *BusinessCode) error

	businessCodeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	businessCodeType                 = reflect.TypeOf(&BusinessCode{})
	businessCodeMapping              = queries.MakeStructMapping(businessCodeType)
	businessCodePrimaryKeyMapping, _ = queries.BindMapping(businessCodeType, businessCodeMapping, businessCodePrimaryKeyColumns)
	businessCodeInsertCacheMut       sync.RWMutex
	businessCodeInsertCache          = make(map[string]insertCache)
	businessCodeUpdateCacheMut       sync.RWMutex
	businessCodeUpdateCache          = make(map[string]updateCache)
	businessCodeUpsertCacheMut       sync.RWMutex
	businessCodeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var businessCodeAfterSelectHooks []BusinessCodeHook

var businessCodeBeforeInsertHooks []BusinessCodeHook
var businessCodeAfterInsertHooks []BusinessCodeHook

var businessCodeBeforeUpdateHooks []BusinessCodeHook
var businessCodeAfterUpdateHooks []BusinessCodeHook

var businessCodeBeforeDeleteHooks []BusinessCodeHook
var businessCodeAfterDeleteHooks []BusinessCodeHook

var businessCodeBeforeUpsertHooks []BusinessCodeHook
var businessCodeAfterUpsertHooks []BusinessCodeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BusinessCode) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BusinessCode) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BusinessCode) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BusinessCode) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BusinessCode) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BusinessCode) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BusinessCode) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BusinessCode) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BusinessCode) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range businessCodeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBusinessCodeHook registers your hook function for all future operations.
func AddBusinessCodeHook(hookPoint boil.HookPoint, businessCodeHook BusinessCodeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		businessCodeAfterSelectHooks = append(businessCodeAfterSelectHooks, businessCodeHook)
	case boil.BeforeInsertHook:
		businessCodeBeforeInsertHooks = append(businessCodeBeforeInsertHooks, businessCodeHook)
	case boil.AfterInsertHook:
		businessCodeAfterInsertHooks = append(businessCodeAfterInsertHooks, businessCodeHook)
	case boil.BeforeUpdateHook:
		businessCodeBeforeUpdateHooks = append(businessCodeBeforeUpdateHooks, businessCodeHook)
	case boil.AfterUpdateHook:
		businessCodeAfterUpdateHooks = append(businessCodeAfterUpdateHooks, businessCodeHook)
	case boil.BeforeDeleteHook:
		businessCodeBeforeDeleteHooks = append(businessCodeBeforeDeleteHooks, businessCodeHook)
	case boil.AfterDeleteHook:
		businessCodeAfterDeleteHooks = append(businessCodeAfterDeleteHooks, businessCodeHook)
	case boil.BeforeUpsertHook:
		businessCodeBeforeUpsertHooks = append(businessCodeBeforeUpsertHooks, businessCodeHook)
	case boil.AfterUpsertHook:
		businessCodeAfterUpsertHooks = append(businessCodeAfterUpsertHooks, businessCodeHook)
	}
}

// One returns a single businessCode record from the query.
func (q businessCodeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BusinessCode, error) {
	o := &BusinessCode{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for business_code")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all BusinessCode records from the query.
func (q businessCodeQuery) All(ctx context.Context, exec boil.ContextExecutor) (BusinessCodeSlice, error) {
	var o []*BusinessCode

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BusinessCode slice")
	}

	if len(businessCodeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all BusinessCode records in the query.
func (q businessCodeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count business_code rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q businessCodeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if business_code exists")
	}

	return count > 0, nil
}

// Organisations retrieves all the organisation's Organisations with an executor.
func (o *BusinessCode) Organisations(mods ...qm.QueryMod) organisationQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"organisation\".\"business_code_id\"=?", o.ID),
	)

	return Organisations(queryMods...)
}

// LoadOrganisations allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (businessCodeL) LoadOrganisations(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBusinessCode interface{}, mods queries.Applicator) error {
	var slice []*BusinessCode
	var object *BusinessCode

	if singular {
		var ok bool
		object, ok = maybeBusinessCode.(*BusinessCode)
		if !ok {
			object = new(BusinessCode)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBusinessCode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBusinessCode))
			}
		}
	} else {
		s, ok := maybeBusinessCode.(*[]*BusinessCode)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBusinessCode)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBusinessCode))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &businessCodeR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &businessCodeR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`organisation`),
		qm.WhereIn(`organisation.business_code_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load organisation")
	}

	var resultSlice []*Organisation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice organisation")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on organisation")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for organisation")
	}

	if len(organisationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Organisations = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &organisationR{}
			}
			foreign.R.BusinessCode = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.BusinessCodeID {
				local.R.Organisations = append(local.R.Organisations, foreign)
				if foreign.R == nil {
					foreign.R = &organisationR{}
				}
				foreign.R.BusinessCode = local
				break
			}
		}
	}

	return nil
}

// AddOrganisations adds the given related objects to the existing relationships
// of the business_code, optionally inserting them as new records.
// Appends related to o.R.Organisations.
// Sets related.R.BusinessCode appropriately.
func (o *BusinessCode) AddOrganisations(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Organisation) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BusinessCodeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"organisation\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"business_code_id"}),
				strmangle.WhereClause("\"", "\"", 2, organisationPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BusinessCodeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &businessCodeR{
			Organisations: related,
		}
	} else {
		o.R.Organisations = append(o.R.Organisations, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &organisationR{
				BusinessCode: o,
			}
		} else {
			rel.R.BusinessCode = o
		}
	}
	return nil
}

// BusinessCodes retrieves all the records using an executor.
func BusinessCodes(mods ...qm.QueryMod) businessCodeQuery {
	mods = append(mods, qm.From("\"business_code\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"business_code\".*"})
	}

	return businessCodeQuery{q}
}

// FindBusinessCode retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBusinessCode(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*BusinessCode, error) {
	businessCodeObj := &BusinessCode{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"business_code\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, businessCodeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from business_code")
	}

	if err = businessCodeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return businessCodeObj, err
	}

	return businessCodeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BusinessCode) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no business_code provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(businessCodeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	businessCodeInsertCacheMut.RLock()
	cache, cached := businessCodeInsertCache[key]
	businessCodeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			businessCodeAllColumns,
			businessCodeColumnsWithDefault,
			businessCodeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(businessCodeType, businessCodeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(businessCodeType, businessCodeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"business_code\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"business_code\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into business_code")
	}

	if !cached {
		businessCodeInsertCacheMut.Lock()
		businessCodeInsertCache[key] = cache
		businessCodeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the BusinessCode.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BusinessCode) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	businessCodeUpdateCacheMut.RLock()
	cache, cached := businessCodeUpdateCache[key]
	businessCodeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			businessCodeAllColumns,
			businessCodePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update business_code, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"business_code\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, businessCodePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(businessCodeType, businessCodeMapping, append(wl, businessCodePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update business_code row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for business_code")
	}

	if !cached {
		businessCodeUpdateCacheMut.Lock()
		businessCodeUpdateCache[key] = cache
		businessCodeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q businessCodeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for business_code")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for business_code")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BusinessCodeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), businessCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"business_code\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, businessCodePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in businessCode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all businessCode")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BusinessCode) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no business_code provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(businessCodeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	businessCodeUpsertCacheMut.RLock()
	cache, cached := businessCodeUpsertCache[key]
	businessCodeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			businessCodeAllColumns,
			businessCodeColumnsWithDefault,
			businessCodeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			businessCodeAllColumns,
			businessCodePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert business_code, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(businessCodePrimaryKeyColumns))
			copy(conflict, businessCodePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"business_code\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(businessCodeType, businessCodeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(businessCodeType, businessCodeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert business_code")
	}

	if !cached {
		businessCodeUpsertCacheMut.Lock()
		businessCodeUpsertCache[key] = cache
		businessCodeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single BusinessCode record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BusinessCode) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BusinessCode provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), businessCodePrimaryKeyMapping)
	sql := "DELETE FROM \"business_code\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from business_code")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for business_code")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q businessCodeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no businessCodeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from business_code")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for business_code")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BusinessCodeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(businessCodeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), businessCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"business_code\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, businessCodePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from businessCode slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for business_code")
	}

	if len(businessCodeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BusinessCode) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBusinessCode(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BusinessCodeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BusinessCodeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), businessCodePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"business_code\".* FROM \"business_code\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, businessCodePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BusinessCodeSlice")
	}

	*o = slice

	return nil
}

// BusinessCodeExists checks if the BusinessCode row exists.
func BusinessCodeExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"business_code\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if business_code exists")
	}

	return exists, nil
}

// Exists checks if the BusinessCode row exists.
func (o *BusinessCode) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BusinessCodeExists(ctx, exec, o.ID)
}
