// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Sa4 is an object representing the database table.
type Sa4 struct {
	ID   int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Code int    `boil:"code" json:"code" toml:"code" yaml:"code"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *sa4R `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sa4L  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var Sa4Columns = struct {
	ID   string
	Code string
	Name string
}{
	ID:   "id",
	Code: "code",
	Name: "name",
}

var Sa4TableColumns = struct {
	ID   string
	Code string
	Name string
}{
	ID:   "sa4.id",
	Code: "sa4.code",
	Name: "sa4.name",
}

// Generated where

var Sa4Where = struct {
	ID   whereHelperint
	Code whereHelperint
	Name whereHelperstring
}{
	ID:   whereHelperint{field: "\"sa4\".\"id\""},
	Code: whereHelperint{field: "\"sa4\".\"code\""},
	Name: whereHelperstring{field: "\"sa4\".\"name\""},
}

// Sa4Rels is where relationship names are stored.
var Sa4Rels = struct {
	Postcodes string
}{
	Postcodes: "Postcodes",
}

// sa4R is where relationships are stored.
type sa4R struct {
	Postcodes PostcodeSlice `boil:"Postcodes" json:"Postcodes" toml:"Postcodes" yaml:"Postcodes"`
}

// NewStruct creates a new relationship struct
func (*sa4R) NewStruct() *sa4R {
	return &sa4R{}
}

func (r *sa4R) GetPostcodes() PostcodeSlice {
	if r == nil {
		return nil
	}
	return r.Postcodes
}

// sa4L is where Load methods for each relationship are stored.
type sa4L struct{}

var (
	sa4AllColumns            = []string{"id", "code", "name"}
	sa4ColumnsWithoutDefault = []string{"code", "name"}
	sa4ColumnsWithDefault    = []string{"id"}
	sa4PrimaryKeyColumns     = []string{"id"}
	sa4GeneratedColumns      = []string{}
)

type (
	// Sa4Slice is an alias for a slice of pointers to Sa4.
	// This should almost always be used instead of []Sa4.
	Sa4Slice []*Sa4
	// Sa4Hook is the signature for custom Sa4 hook methods
	Sa4Hook func(context.Context, boil.ContextExecutor, *Sa4) error

	sa4Query struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sa4Type                 = reflect.TypeOf(&Sa4{})
	sa4Mapping              = queries.MakeStructMapping(sa4Type)
	sa4PrimaryKeyMapping, _ = queries.BindMapping(sa4Type, sa4Mapping, sa4PrimaryKeyColumns)
	sa4InsertCacheMut       sync.RWMutex
	sa4InsertCache          = make(map[string]insertCache)
	sa4UpdateCacheMut       sync.RWMutex
	sa4UpdateCache          = make(map[string]updateCache)
	sa4UpsertCacheMut       sync.RWMutex
	sa4UpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var sa4AfterSelectHooks []Sa4Hook

var sa4BeforeInsertHooks []Sa4Hook
var sa4AfterInsertHooks []Sa4Hook

var sa4BeforeUpdateHooks []Sa4Hook
var sa4AfterUpdateHooks []Sa4Hook

var sa4BeforeDeleteHooks []Sa4Hook
var sa4AfterDeleteHooks []Sa4Hook

var sa4BeforeUpsertHooks []Sa4Hook
var sa4AfterUpsertHooks []Sa4Hook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Sa4) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4AfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Sa4) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4BeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Sa4) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4AfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Sa4) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4BeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Sa4) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4AfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Sa4) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4BeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Sa4) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4AfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Sa4) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4BeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Sa4) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sa4AfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSa4Hook registers your hook function for all future operations.
func AddSa4Hook(hookPoint boil.HookPoint, sa4Hook Sa4Hook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		sa4AfterSelectHooks = append(sa4AfterSelectHooks, sa4Hook)
	case boil.BeforeInsertHook:
		sa4BeforeInsertHooks = append(sa4BeforeInsertHooks, sa4Hook)
	case boil.AfterInsertHook:
		sa4AfterInsertHooks = append(sa4AfterInsertHooks, sa4Hook)
	case boil.BeforeUpdateHook:
		sa4BeforeUpdateHooks = append(sa4BeforeUpdateHooks, sa4Hook)
	case boil.AfterUpdateHook:
		sa4AfterUpdateHooks = append(sa4AfterUpdateHooks, sa4Hook)
	case boil.BeforeDeleteHook:
		sa4BeforeDeleteHooks = append(sa4BeforeDeleteHooks, sa4Hook)
	case boil.AfterDeleteHook:
		sa4AfterDeleteHooks = append(sa4AfterDeleteHooks, sa4Hook)
	case boil.BeforeUpsertHook:
		sa4BeforeUpsertHooks = append(sa4BeforeUpsertHooks, sa4Hook)
	case boil.AfterUpsertHook:
		sa4AfterUpsertHooks = append(sa4AfterUpsertHooks, sa4Hook)
	}
}

// One returns a single sa4 record from the query.
func (q sa4Query) One(ctx context.Context, exec boil.ContextExecutor) (*Sa4, error) {
	o := &Sa4{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for sa4")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Sa4 records from the query.
func (q sa4Query) All(ctx context.Context, exec boil.ContextExecutor) (Sa4Slice, error) {
	var o []*Sa4

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Sa4 slice")
	}

	if len(sa4AfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Sa4 records in the query.
func (q sa4Query) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count sa4 rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sa4Query) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if sa4 exists")
	}

	return count > 0, nil
}

// Postcodes retrieves all the postcode's Postcodes with an executor.
func (o *Sa4) Postcodes(mods ...qm.QueryMod) postcodeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"postcode\".\"sa4_id\"=?", o.ID),
	)

	return Postcodes(queryMods...)
}

// LoadPostcodes allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (sa4L) LoadPostcodes(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSa4 interface{}, mods queries.Applicator) error {
	var slice []*Sa4
	var object *Sa4

	if singular {
		var ok bool
		object, ok = maybeSa4.(*Sa4)
		if !ok {
			object = new(Sa4)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSa4)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSa4))
			}
		}
	} else {
		s, ok := maybeSa4.(*[]*Sa4)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSa4)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSa4))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &sa4R{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sa4R{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`postcode`),
		qm.WhereIn(`postcode.sa4_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load postcode")
	}

	var resultSlice []*Postcode
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice postcode")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on postcode")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for postcode")
	}

	if len(postcodeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Postcodes = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &postcodeR{}
			}
			foreign.R.Sa4 = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.Sa4ID) {
				local.R.Postcodes = append(local.R.Postcodes, foreign)
				if foreign.R == nil {
					foreign.R = &postcodeR{}
				}
				foreign.R.Sa4 = local
				break
			}
		}
	}

	return nil
}

// AddPostcodes adds the given related objects to the existing relationships
// of the sa4, optionally inserting them as new records.
// Appends related to o.R.Postcodes.
// Sets related.R.Sa4 appropriately.
func (o *Sa4) AddPostcodes(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Postcode) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.Sa4ID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"postcode\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"sa4_id"}),
				strmangle.WhereClause("\"", "\"", 2, postcodePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.Sa4ID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &sa4R{
			Postcodes: related,
		}
	} else {
		o.R.Postcodes = append(o.R.Postcodes, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &postcodeR{
				Sa4: o,
			}
		} else {
			rel.R.Sa4 = o
		}
	}
	return nil
}

// SetPostcodes removes all previously related items of the
// sa4 replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Sa4's Postcodes accordingly.
// Replaces o.R.Postcodes with related.
// Sets related.R.Sa4's Postcodes accordingly.
func (o *Sa4) SetPostcodes(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Postcode) error {
	query := "update \"postcode\" set \"sa4_id\" = null where \"sa4_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Postcodes {
			queries.SetScanner(&rel.Sa4ID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Sa4 = nil
		}
		o.R.Postcodes = nil
	}

	return o.AddPostcodes(ctx, exec, insert, related...)
}

// RemovePostcodes relationships from objects passed in.
// Removes related items from R.Postcodes (uses pointer comparison, removal does not keep order)
// Sets related.R.Sa4.
func (o *Sa4) RemovePostcodes(ctx context.Context, exec boil.ContextExecutor, related ...*Postcode) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.Sa4ID, nil)
		if rel.R != nil {
			rel.R.Sa4 = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("sa4_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Postcodes {
			if rel != ri {
				continue
			}

			ln := len(o.R.Postcodes)
			if ln > 1 && i < ln-1 {
				o.R.Postcodes[i] = o.R.Postcodes[ln-1]
			}
			o.R.Postcodes = o.R.Postcodes[:ln-1]
			break
		}
	}

	return nil
}

// Sa4s retrieves all the records using an executor.
func Sa4s(mods ...qm.QueryMod) sa4Query {
	mods = append(mods, qm.From("\"sa4\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"sa4\".*"})
	}

	return sa4Query{q}
}

// FindSa4 retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSa4(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Sa4, error) {
	sa4Obj := &Sa4{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"sa4\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, sa4Obj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from sa4")
	}

	if err = sa4Obj.doAfterSelectHooks(ctx, exec); err != nil {
		return sa4Obj, err
	}

	return sa4Obj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Sa4) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sa4 provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sa4ColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sa4InsertCacheMut.RLock()
	cache, cached := sa4InsertCache[key]
	sa4InsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sa4AllColumns,
			sa4ColumnsWithDefault,
			sa4ColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sa4Type, sa4Mapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sa4Type, sa4Mapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"sa4\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"sa4\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into sa4")
	}

	if !cached {
		sa4InsertCacheMut.Lock()
		sa4InsertCache[key] = cache
		sa4InsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Sa4.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Sa4) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sa4UpdateCacheMut.RLock()
	cache, cached := sa4UpdateCache[key]
	sa4UpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sa4AllColumns,
			sa4PrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update sa4, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"sa4\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, sa4PrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sa4Type, sa4Mapping, append(wl, sa4PrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update sa4 row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for sa4")
	}

	if !cached {
		sa4UpdateCacheMut.Lock()
		sa4UpdateCache[key] = cache
		sa4UpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q sa4Query) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for sa4")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for sa4")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o Sa4Slice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sa4PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"sa4\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, sa4PrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in sa4 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all sa4")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Sa4) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sa4 provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sa4ColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sa4UpsertCacheMut.RLock()
	cache, cached := sa4UpsertCache[key]
	sa4UpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			sa4AllColumns,
			sa4ColumnsWithDefault,
			sa4ColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			sa4AllColumns,
			sa4PrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert sa4, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(sa4PrimaryKeyColumns))
			copy(conflict, sa4PrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"sa4\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(sa4Type, sa4Mapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sa4Type, sa4Mapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert sa4")
	}

	if !cached {
		sa4UpsertCacheMut.Lock()
		sa4UpsertCache[key] = cache
		sa4UpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Sa4 record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Sa4) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Sa4 provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sa4PrimaryKeyMapping)
	sql := "DELETE FROM \"sa4\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from sa4")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for sa4")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sa4Query) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no sa4Query provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sa4")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sa4")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o Sa4Slice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sa4BeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sa4PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"sa4\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sa4PrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sa4 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sa4")
	}

	if len(sa4AfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Sa4) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSa4(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *Sa4Slice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := Sa4Slice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sa4PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"sa4\".* FROM \"sa4\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sa4PrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in Sa4Slice")
	}

	*o = slice

	return nil
}

// Sa4Exists checks if the Sa4 row exists.
func Sa4Exists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"sa4\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if sa4 exists")
	}

	return exists, nil
}

// Exists checks if the Sa4 row exists.
func (o *Sa4) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return Sa4Exists(ctx, exec, o.ID)
}
